spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: InnerJoin77
    url: jdbc:postgresql://localhost:5432/
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
